# embarrassing amount of copy paste here, can be made neater.
sortndvi <- function(ndvi, reference){
  jan <- c(rast(ndvi[[1]]), rast(ndvi[[2]]), rast(ndvi[[3]]), rast(ndvi[[4]]), rast(ndvi[[5]]))
  feb <- c(rast(ndvi[[6]]), rast(ndvi[[7]]), rast(ndvi[[8]]), rast(ndvi[[9]]))
  mar <- c(rast(ndvi[[10]]), rast(ndvi[[11]]), rast(ndvi[[12]]), rast(ndvi[[13]]))
  apr <- c(rast(ndvi[[14]]), rast(ndvi[[15]]), rast(ndvi[[16]]), rast(ndvi[[17]]), rast(ndvi[[18]]))
  may <- c(rast(ndvi[[19]]), rast(ndvi[[20]]), rast(ndvi[[21]]), rast(ndvi[[22]]))
  jun <- c(rast(ndvi[[23]]), rast(ndvi[[24]]), rast(ndvi[[25]]), rast(ndvi[[26]]))
  jul <- c(rast(ndvi[[27]]), rast(ndvi[[28]]), rast(ndvi[[29]]), rast(ndvi[[30]]), rast(ndvi[[31]]))
  aug <- c(rast(ndvi[[32]]), rast(ndvi[[33]]), rast(ndvi[[34]]), rast(ndvi[[35]]))
  sep <- c(rast(ndvi[[36]]), rast(ndvi[[37]]), rast(ndvi[[38]]), rast(ndvi[[39]]))
  oct <- c(rast(ndvi[[40]]), rast(ndvi[[41]]), rast(ndvi[[42]]), rast(ndvi[[43]]), rast(ndvi[[44]]))
  nov <- c(rast(ndvi[[45]]), rast(ndvi[[46]]), rast(ndvi[[47]]), rast(ndvi[[48]]))
  dec <- c(rast(ndvi[[49]]), rast(ndvi[[50]]), rast(ndvi[[51]]), rast(ndvi[[52]]))
  
  jan <- app(jan, mean)                                                                                                                        
  feb <- app(feb, mean)
  mar <- app(mar, mean)
  apr <- app(apr, mean)
  may <- app(may, mean)
  jun <- app(jun, mean)
  jul <- app(jul, mean)
  aug <- app(aug, mean)
  sep <- app(sep, mean)
  oct <- app(oct, mean)
  nov <- app(nov, mean)
  dec <- app(dec, mean)
  
  jan <- resample(jan, reference)
  feb <- resample(feb, reference)
  mar <- resample(mar, reference)
  apr <- resample(apr, reference)
  may <- resample(may, reference)
  jun <- resample(jun, reference)
  jul <- resample(jul, reference)
  aug <- resample(aug, reference)
  sep <- resample(sep, reference)
  oct <- resample(oct, reference)
  nov <- resample(nov, reference)
  dec <- resample(dec, reference)
  
  jan <- mask(jan, reference)
  feb <- mask(feb, reference)
  mar <- mask(mar, reference)
  apr <- mask(apr, reference)
  may <- mask(may, reference)
  jun <- mask(jun, reference)
  jul <- mask(jul, reference)
  aug <- mask(aug, reference)
  sep <- mask(sep, reference)
  oct <- mask(oct, reference)
  nov <- mask(nov, reference)
  dec <- mask(dec, reference)
ndvis <- list(jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec)
return(ndvis)
}
